#!/usr/bin/env bash
#
# Pull all four pinned Gemma 4 variants via Ollama.
#
# Idempotent: skips models that are already present. Streams progress for
# pulls that actually run. Fails fast with a clear message if Ollama is
# missing or unreachable.
#
# Variant rationale lives in docs/DECISIONS.md (ADR-001) and the per-tag
# digests live in runtime.lock.json (regenerated by `pnpm lock-runtime`).

set -euo pipefail

readonly MODELS=(
  "gemma4:e4b-it-q8_0"
  "gemma4:26b-a4b-it-q8_0"
  "gemma4:31b-it-q8_0"
)

if ! command -v ollama >/dev/null 2>&1; then
  echo "error: ollama is not installed; install from https://ollama.com/download and re-run" >&2
  exit 1
fi

if ! curl -sf "http://localhost:11434/api/tags" >/dev/null 2>&1; then
  echo "error: Ollama daemon is not reachable at http://localhost:11434; start it with 'ollama serve' or open the menubar app and re-run" >&2
  exit 1
fi

list_output="$(ollama list)"

is_pulled() {
  local name="$1"
  printf '%s\n' "$list_output" | awk 'NR>1 {print $1}' | grep -qx "$name"
}

show_summary() {
  local name="$1"
  echo "info: $name"
  ollama show "$name" 2>/dev/null | sed 's/^/  /' || echo "  (no summary available)"
  echo
}

for model in "${MODELS[@]}"; do
  if is_pulled "$model"; then
    echo "skip: $model already pulled"
  else
    echo "pull: $model"
    ollama pull "$model"
    list_output="$(ollama list)"
  fi
  show_summary "$model"
done

echo "done: all pinned Gemma 4 variants present locally"
echo "next: run 'pnpm lock-runtime' to regenerate runtime.lock.json with current digests"
